services:
  web:
    build: .
    volumes:
      - ./public:/app/public
      - /home/hmma/databases:/databases
      - /etc/ssl/cafe-menu:/etc/ssl/cafe-menu
    ports:
      - "3000:3000"
    env_file:
      - .env

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3001:3000"
    environment:
      MB_DB_FILE: /databases/cafe.sqlite
    volumes:
      - /home/hmma/databases:/databases
      - ./metabase-data:/metabase-data
